### ISSUE TITLE
Ideas for improvements

### ISSUE THREAD

**Issue by textbook** [Percona-Lab/codeceptjs-saucehelper#3]
I think this is a handy idea for a helper, but the current implementation means we ended up rewriting it for the project I'm working on. A few suggested improvements:

 - [ ] Use the built-in [`REST`][1] helper
 - [ ] Use [`output`][2] for logs 
 - [ ] Get user and key from the appropriate helper's config, rather than requiring duplication
 - [ ] Handle the [EU DC][3] option

Would you be interested in PRs for any or all of these?

 [1]: https://codecept.io/helpers/REST
 [2]: https://codecept.io/api/output
 [3]: https://wiki.saucelabs.com/display/DOCS/Sauce+Labs+European+Data+Center+Configuration+Information

**Comment by puneet0191** [comment]
@textbook I would be glad if you could help with these, I agree with your ideas thanks
